/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversordeunidades;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboOrigen = new javax.swing.JComboBox<>();
        cboDestino = new javax.swing.JComboBox<>();
        btnConvertir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(159, 159, 167));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Conversor de Unidades");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Categoria:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 94, 96, -1));

        cboCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccione]", "MONEDA", "LONGITUD", "PESO", "TEMPERATURA", "VOLUMEN", " " }));
        cboCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCategoriaItemStateChanged(evt);
            }
        });
        getContentPane().add(cboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 125, 168, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        txtCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 190, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Unidad de Origen");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Unidad de Destino");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        cboOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboOrigenActionPerformed(evt);
            }
        });
        getContentPane().add(cboOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 159, -1));

        cboDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(cboDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 160, -1));

        btnConvertir.setBackground(new java.awt.Color(0, 0, 153));
        btnConvertir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConvertir.setForeground(new java.awt.Color(255, 255, 255));
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 372, -1, 65));

        btnLimpiar.setBackground(new java.awt.Color(255, 51, 51));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 372, -1, 65));

        btnHistorial.setBackground(new java.awt.Color(51, 153, 0));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setText("Historial");
        getContentPane().add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 375, 93, 45));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Resultado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 135, -1));

        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 207, 57));

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Categoría", "Valor Origen", "Unidad Origen", "Valor Convertido"
            }
        ));
        jScrollPane1.setViewportView(tblHistorial);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 340, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void cboDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDestinoActionPerformed

    private void cboCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCategoriaItemStateChanged
        // TODO add your handling code here:
        String  categoria = cboCategoria.getSelectedItem().toString();
                
        switch (categoria){
            case "MONEDA" -> {
                cboOrigen.removeAllItems();
                
                cboOrigen.addItem("Soles");
                cboOrigen.addItem("Euros");
                cboOrigen.addItem("Dolares");
                
                cboDestino.removeAllItems();
                
                cboDestino.addItem("Soles");
                cboDestino.addItem("Euros");
                cboDestino.addItem("Dolares");
            }
                
            case "LONGITUD" -> {
                cboOrigen.removeAllItems();
                cboOrigen.addItem("Metro");
                cboOrigen.addItem("Pulgada");
                cboOrigen.addItem("Pies");
                
                cboDestino.removeAllItems();
                cboDestino.addItem("Metro");
                cboDestino.addItem("Pulgada");
                cboDestino.addItem("Pies");
            }
                
            case "PESO" -> {
                cboOrigen.removeAllItems();
                cboOrigen.addItem("Kilogramo");
                cboOrigen.addItem("Libra");
                cboOrigen.addItem("Onza");
                
                cboDestino.removeAllItems();
                cboDestino.addItem("Kilogramo");
                cboDestino.addItem("Libra");
                cboDestino.addItem("Onza");
            }
                
            case "TEMPERATURA" -> {
                cboOrigen.removeAllItems();
                cboOrigen.addItem("Celcius");
                cboOrigen.addItem("Fahrenheit");
                cboOrigen.addItem("Kelvin");
                
                cboDestino.removeAllItems();
                cboDestino.addItem("Celcius");
                cboDestino.addItem("Fahrenheit");
                cboDestino.addItem("Kelvin");
            }
                
            case "VOLUMEN" -> {
                cboOrigen.removeAllItems();
                cboOrigen.addItem("Litro");
                cboOrigen.addItem("Metro Cúbico");
                cboOrigen.addItem("Mililitro");
                
                cboDestino.removeAllItems();
                cboDestino.addItem("Litro");
                cboDestino.addItem("Metro Cúbico");
                cboDestino.addItem("Mililitro");
            }
        }
    }//GEN-LAST:event_cboCategoriaItemStateChanged

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        double result = 0;
        String categoria = cboCategoria.getSelectedItem().toString();
        
        String Opcion1= cboOrigen.getSelectedItem().toString();
        String Opcion2 = cboDestino.getSelectedItem().toString();
        
        if(categoria.equals("MONEDA")){
            if(Opcion1 ==Opcion2){
                JOptionPane.showMessageDialog(rootPane, "No se puede realzia la conversion, los elementos son iguales");
            }else{
                // Soles a dolares
                if(Opcion1.equals("Soles") && Opcion2.equals("Dolares")){
                    result = Double.parseDouble(txtCantidad.getText()) * 3.57;
                    txtResultado.setText(result+" Dolar(es)");
                }

                if(Opcion1.equals("Soles") && Opcion2.equals("Euros")){
                    result = Double.parseDouble(txtCantidad.getText()) * 4.20;
                    txtResultado.setText(result+" Euro(s)");
                }
            }
        }
        
        
        if("LONGITUD".equals(categoria)){
            if(Opcion1 ==Opcion2){
                JOptionPane.showMessageDialog(rootPane, "No se puede realzia la conversion, los elementos son iguales");
            }else{
                // Soles a dolares
                if(Opcion1.equals("Soles") && Opcion2.equals("Dolar")){
                    result = Double.parseDouble(txtCantidad.getText()) * 3.57;
                    txtResultado.setText(result+" Dolar(es)");
                }

                if(Opcion1.equals("Soles") && Opcion2.equals("Euro")){
                    result = Double.parseDouble(txtCantidad.getText()) * 4.20;
                    txtResultado.setText(result+" Euro(s)");
                }
            }
        }
                            
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void cboOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JComboBox<String> cboDestino;
    private javax.swing.JComboBox<String> cboOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistorial;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
